nome = str(input('Digite seu nome: ')).strip()
separacao = nome.split()
print ('Seu nome é {}' .format(nome))
print ('seu primeiro nome é {}'. format(separacao[0]))
print ('seu ultimo nome é {}'. format(separacao[-1]))
